printl("\nuz_desert Nav Mesh Fixes\n")

//Change 1: Fix saferoom not being fully-checkpointed

local Safe1 = NavMesh.GetNavAreaByID(32109)
Safe1.SetSpawnAttributes(2048)

//Change 2: Fix glitch spots due to one-way or orphaned nav meshes.

local Saferoom1 = NavMesh.GetNavAreaByID(32474)
local Saferoom2 = NavMesh.GetNavAreaByID(32138)
Saferoom1.ConnectTo(Saferoom2,-1)
Saferoom2.ConnectTo(Saferoom1,-1)

local Canyon1 = NavMesh.GetNavAreaByID(19173)
local Canyon2 = NavMesh.GetNavAreaByID(37421)
Canyon1.ConnectTo(Canyon2,-1)

local Airplane1 = NavMesh.GetNavAreaByID(37367)
local Airplane2 = NavMesh.GetNavAreaByID(19398)
local Airplane3 = NavMesh.GetNavAreaByID(19397)
local Airplane4 = NavMesh.GetNavAreaByID(37360)
local Airplane5 = NavMesh.GetNavAreaByID(32624)
local Airplane6 = NavMesh.GetNavAreaByID(4765)
local Airplane7 = NavMesh.GetNavAreaByID(618)
local Airplane8 = NavMesh.GetNavAreaByID(19026)
Airplane1.ConnectTo(Airplane2,-1)
Airplane2.ConnectTo(Airplane1,-1)
Airplane3.ConnectTo(Airplane4,-1)
Airplane4.ConnectTo(Airplane3,-1)
Airplane5.ConnectTo(Airplane6,-1)
Airplane7.ConnectTo(Airplane8,-1)

local MountedGun1 = NavMesh.GetNavAreaByID(51442)
local MountedGun2 = NavMesh.GetNavAreaByID(30953)
local MountedGun3 = NavMesh.GetNavAreaByID(22243)
local MountedGun4 = NavMesh.GetNavAreaByID(22237)
MountedGun1.ConnectTo(MountedGun2,-1)
MountedGun2.ConnectTo(MountedGun1,-1)
MountedGun3.ConnectTo(MountedGun4,-1)
MountedGun4.ConnectTo(MountedGun3,-1)

local GunBunker1 = NavMesh.GetNavAreaByID(316)
local GunBunker2 = NavMesh.GetNavAreaByID(35841)
GunBunker1.ConnectTo(GunBunker2,-1)
GunBunker2.ConnectTo(GunBunker1,-1)

local TruckBunker1 = NavMesh.GetNavAreaByID(291)
local TruckBunker2 = NavMesh.GetNavAreaByID(10459)
local TruckBunker3 = NavMesh.GetNavAreaByID(34238)
local TruckBunker4 = NavMesh.GetNavAreaByID(10460)
local TruckBunker5 = NavMesh.GetNavAreaByID(1403)
local TruckBunker6 = NavMesh.GetNavAreaByID(28777)
local TruckBunker7 = NavMesh.GetNavAreaByID(2098)
local TruckBunker8 = NavMesh.GetNavAreaByID(28754)
local TruckBunker9 = NavMesh.GetNavAreaByID(27784)
local TruckBunker10 = NavMesh.GetNavAreaByID(27781)
TruckBunker1.ConnectTo(TruckBunker2,-1)
TruckBunker3.ConnectTo(TruckBunker4,-1)
TruckBunker5.ConnectTo(TruckBunker6,-1)
TruckBunker6.ConnectTo(TruckBunker5,-1)
TruckBunker7.ConnectTo(TruckBunker8,-1)
TruckBunker8.ConnectTo(TruckBunker7,-1)
TruckBunker9.ConnectTo(TruckBunker10,-1)
TruckBunker10.ConnectTo(TruckBunker9,-1)

local TruckBunkerTruck1 = NavMesh.GetNavAreaByID(29041)
local TruckBunkerTruck2 = NavMesh.GetNavAreaByID(5762)
local TruckBunkerTruck3 = NavMesh.GetNavAreaByID(29044)
local TruckBunkerTruck4 = NavMesh.GetNavAreaByID(132)
local TruckBunkerTruck5 = NavMesh.GetNavAreaByID(28748)
local TruckBunkerTruck7 = NavMesh.GetNavAreaByID(5763)
local TruckBunkerTruck8 = NavMesh.GetNavAreaByID(10504)
TruckBunkerTruck1.ConnectTo(TruckBunkerTruck2,-1)
TruckBunkerTruck2.ConnectTo(TruckBunkerTruck3,-1)
TruckBunkerTruck3.ConnectTo(TruckBunkerTruck2,-1)
TruckBunkerTruck4.ConnectTo(TruckBunkerTruck2,-1)
TruckBunkerTruck3.ConnectTo(TruckBunkerTruck7,-1)
TruckBunkerTruck7.ConnectTo(TruckBunkerTruck3,-1)
TruckBunkerTruck7.ConnectTo(TruckBunkerTruck8,-1)
TruckBunkerTruck8.ConnectTo(TruckBunkerTruck7,-1)

local EndSaferoom1 = NavMesh.GetNavAreaByID(34960)
local EndSaferoom2 = NavMesh.GetNavAreaByID(26460)
EndSaferoom1.ConnectTo(EndSaferoom2,-1)
EndSaferoom2.ConnectTo(EndSaferoom1,-1)

printl("\nNav Mesh Changees applied\n")
