printl("\n[NavFixes] x1m1_cliffs_navfixes initialized\n")

//Fix 1: Fix jesus spots//

//Get nav areas:
//Problematic nav areas
local firsthillNav = NavMesh.GetNavAreaByID(9802)
local firstpulldownNav = NavMesh.GetNavAreaByID(2365)
local benchNav = NavMesh.GetNavAreaByID(3776)
local tractorNav1 = NavMesh.GetNavAreaByID(8555)
local tractorNav2 = NavMesh.GetNavAreaByID(8536)
local tractorNav3 = NavMesh.GetNavAreaByID(3300)
local tractorNav4 = NavMesh.GetNavAreaByID(3223)
local tractorNav5 = NavMesh.GetNavAreaByID(8581)
local tractorNav6 = NavMesh.GetNavAreaByID(8732)
local saloontableNav = NavMesh.GetNavAreaByID(2609)
local endgeneratorNav = NavMesh.GetNavAreaByID(7834)

//Nav areas to connect
local firsthillNavFix = NavMesh.GetNavAreaByID(2462)
local firstpulldownNavFix = NavMesh.GetNavAreaByID(9716)
local benchNavFix = NavMesh.GetNavAreaByID(9296) 
local tractorNavFix1 = NavMesh.GetNavAreaByID(105) 
local tractorNavFix2 = NavMesh.GetNavAreaByID(8753)
local tractorNavFix3 = NavMesh.GetNavAreaByID(280)
local tractorNavFix4 = NavMesh.GetNavAreaByID(449)
local saloontableNavFix = NavMesh.GetNavAreaByID(142)
local endgeneratorNavFix = NavMesh.GetNavAreaByID(9988)

// Bush Nav 
local bushNav1 = NavMesh.GetNavAreaByID(4014)
local bushNav1Fix = NavMesh.GetNavAreaByID(4039)
local bushNav2 = NavMesh.GetNavAreaByID(4015)
local bushNav2Fix = NavMesh.GetNavAreaByID(2107)
local bushNav3 = NavMesh.GetNavAreaByID(4042)
local bushNav4 = NavMesh.GetNavAreaByID(4043)
local bushNav4Fix = NavMesh.GetNavAreaByID(469)
local bushNav5 = NavMesh.GetNavAreaByID(5729)
local bushNav5Fix = NavMesh.GetNavAreaByID(9820)

//Create two-way connection between nav areas
firsthillNavFix.ConnectTo(firsthillNav,-1)
firsthillNav.ConnectTo(firsthillNavFix,-1)
firstpulldownNavFix.ConnectTo(firstpulldownNav,-1)
firstpulldownNav.ConnectTo(firstpulldownNavFix,-1)
benchNavFix.ConnectTo(benchNav,-1)
benchNav.ConnectTo(benchNavFix,-1)
tractorNav1.ConnectTo(tractorNav2,-1)
tractorNav2.ConnectTo(tractorNav1,-1)
tractorNavFix1.ConnectTo(tractorNav2,-1)
tractorNav3.ConnectTo(tractorNavFix2,-1)
tractorNavFix2.ConnectTo(tractorNav3,-1)
tractorNav4.ConnectTo(tractorNav5,-1)
tractorNav5.ConnectTo(tractorNav4,-1)
tractorNav5.ConnectTo(tractorNavFix3,-1)
tractorNavFix3.ConnectTo(tractorNav5,-1)
tractorNav6.ConnectTo(tractorNavFix4,-1)
tractorNavFix4.ConnectTo(tractorNav6,-1)
saloontableNav.ConnectTo(saloontableNavFix,-1)
saloontableNavFix.ConnectTo(saloontableNav,-1)
endgeneratorNav.ConnectTo(endgeneratorNavFix,-1)
endgeneratorNavFix.ConnectTo(endgeneratorNav,-1)
bushNav1.ConnectTo(bushNav1Fix,-1)
bushNav1Fix.ConnectTo(bushNav1,-1)
bushNav2.ConnectTo(bushNav2Fix,-1)
bushNav2Fix.ConnectTo(bushNav2,-1)
bushNav3.ConnectTo(bushNav2Fix,-1)
bushNav2Fix.ConnectTo(bushNav3,-1)
bushNav4.ConnectTo(bushNav4Fix,-1)
bushNav4Fix.ConnectTo(bushNav4,-1)
bushNav5Fix.ConnectTo(bushNav5,-1)

printl("\n[NavFixes] Fix 1 applied\n")
